name: colors_lab

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-lastest
      container:
        image: node:20
      steps:
        - uses: actions/checkout@v3
          with:
            node-version: 20
        - run: npm ci 
        - run: npm test
        - run: npm run build